# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out...
        uses: actions/checkout@v4
        # with:
        #   ref: main
        #   token: ${{ steps.get_workflow_token.outputs.token }}
      - name: Get repo version...
        id: version
        run: |
          echo "REPO_TAG=$(git tag --list --sort=-version:refname "v*" --merged | head -n 1)"
      # - uses: actions/checkout@v4
      # - name: Run a simple command
      #   run: echo "Hello from GitHub Actions!"
